### ISSUE TITLE
how to open the PDFs?

### ISSUE THREAD

**Issue by oren** [JBlocklove/remarkable-daily-pdf#1]
i assume that in the current solution i won't be able to open the PDFs with the built-in reader. just want to verify my assumption.

If that's correct, is it possible to change that so I can use the built-in PDF reader that comes with rm?

**Comment by JBlocklove** [comment]
No, actually, I designed this to be able to work with Xochitl, which is the built-in reader for remarkable. It uses a flattened filesystem that relies on `.content` and `.metadata` files to create the hierarchy, and I created functions that make those files in the `functions` file.

Did you try it and is it not working for you?

**Comment by oren** [comment]
I have not tried it. Do i need a subscription for NY Times? i don't. my usecase is viewing articles on the rm but I don't mind testing it on the NY Times just to help you out.


Currently I download the website as PDF, connect the rm with USB, and than I use this bash script:

```
curl --form file="@$1" http://10.11.99.1/upload
```

**Comment by JBlocklove** [comment]
For what I currently have set up you'd need an NYT subscription since I only really have a crossword script set up, but the next thing on my todo list is to make it more generic so it can automatically pull pretty much any url that can resolve to a pdf. I'll probably get to that in the next couple of days, so if you have a particular website you'd like me to use for my testing I'd be happy to do that to make sure it works for you.

**Comment by oren** [comment]
That's fantastic and will make this tool very useful. I don't have a specific website. Btw, it will be awesome to figure out how to print a reddit and hackernews discussion into a PDF format but that's probably a different challenge.

**Comment by oren** [comment]
btw, in my current work flow I first get rid of any ads and sidebars, and increase the font size using Firefox Reader View or by deleting DOM elements manually and than I print as PDF.

**Comment by JBlocklove** [comment]
I've made the tool able to pull from any url that resolves to a pdf file, which I think it really all this issue is addressing. If I am mistaken please feel free to open a new issue with a specific problem or requested enhancement, but I'm closing this one for now.
