### ISSUE TITLE
Bug: Install script no longer working

### ISSUE THREAD

**Issue by JBlocklove** [JBlocklove/remarkable-daily-pdf#13]
Several users have reported that the install script no longer works correctly: not creating the remarkable-daily-pdf directory from which all of the other functions get called. Seems like the infrastructure of the tools needs a pretty significant overhaul.

**Comment by JBlocklove** [comment]
Rewrote a good portion of the installation and it seems to work now. Will wait to hear back from a couple of users to confirm on their devices as well before I close this.

**Comment by WhenInWome** [comment]
Worked great for me! Initial download took maybe 5s and then it rebooted and the PDF showed up in the correctly named folder within /Crosswords/. Amazing thank you so much! This doesn't check previous downloads does it? Like if I have my RM2 off for a couple days it won't backfill automatically? Maybe a future feature request.

**Comment by JBlocklove** [comment]
Awesome, glad to hear it!

Sadly no automation for handling previous day's downloads as of yet. I'm hoping [rm-hacks](https://github.com/mb1986/rm-hacks) will be implementing a way to add custom UI elements reasonably soon since I'd like to have a way to just select what dates to download and have it pull those straight from the remarkable's interface. In the meantime I have a script I wrote a while ago that you can call with a date range and it will download everything within that range. I need to clean it up before adding it to the repo, but I should have that done in the next couple of days.

**Comment by JBlocklove** [comment]
Closing this issue for now, since it seems the install script is working as expected

**Comment by JBlocklove** [comment]
@WhenInWome just pushed a script and some instructions for downloading a range of dates for the crossword. It's just a script I whipped up for myself so it's not very well automated at the moment, but if you miss a few days or want to grab a selection of crosswords it's a good way to go. Hope you find it useful!

**Comment by WhenInWome** [comment]
Thanks I'll check it out. Just woke my tablet up from sleep this morning and it didn't download today's puzzle, should it have? I tried restarting it and still nothing is showing up in the folder.

**Comment by JBlocklove** [comment]
Darn, I'll reopen the issue then.

Troubleshooting steps:
1. Be patient. There are several steps involved in downloading and moving the pdf, and the more files you have on your remarkable the longer it will take. First, the download service will try to run again once every minute until it succeeds or the program it's running fails. So the remarkable needs to connect to the internet, and then the program will start, but it can still take a few minutes.The remarkable uses a flattened file system that needs to be traversed to make sure files are getting put in the right spot. This can take a while.

2. Run `systemctl status download-pdfs.timer` and `systemctl status download-pdfs.service`. Copy those outputs and share them.

3. Run `systemctl start download-pdfs.service`, wait a minute, and then copy the end of the output of `journalctl`, which should include all of the output from running the service

Once we have those outputs I can help figure out what's going on

**Comment by WhenInWome** [comment]
Huh something weird just happened, I hadn't had time to troubleshoot this yet but after turning it on today and flipping around between some files it restarted and now I have the files from Friday (run manually during setup), nothing from the weekend, and then Monday and Tuesday as well. I don't remember it ever restarting yesterday but it could have happened while I wasn't looking at it. Not sure how it worked Monday/Tuesday and not over the weekend because I'm pretty sure it was on every day but who knows.

I'll keep an eye on it and see if it keeps working or if I can determine some pattern.

**Comment by JBlocklove** [comment]
Any updates? Has it been working since?

**Comment by WhenInWome** [comment]
Yep been working since! I think you can close this one again, those first couple days I must have just been shutting it down before it fetched.

**Comment by JBlocklove** [comment]
Sounds good, glad it's working!

**Comment by AEATylerMoore** [comment]
Stopped working for me again on Aug. 28th (Aug. 27th download worked fine), is it still working for you? Been using my RM2 daily for extended periods so not an issue of waiting this time.

**Comment by JBlocklove** [comment]
My first guess is that your cookie for your NYT credentials expired (assuming that's what you're downloading). I think this happens every 6 months, if I remember correctly. A quick check for that would be to `ssh` into the remarkable and just try to `wget` the pdf on its own. If you get a `401 Unauthorized` error, your cookie has likely expired.

Once again, assuming you're downloading the NYT crossword, you can run the command at the top here, and if you see the same error, you just need to download a new cookie:
```
reMarkable: ~/ wget https://www.nytimes.com/svc/crosswords/v2/puzzle/print/Sep0124.pdf
Connecting to www.nytimes.com (151.101.45.164:443)
wget: note: TLS certificate validation not implemented
wget: server returned error: HTTP/1.1 401 Unauthorized
```

**Comment by WhenInWome** [comment]
Just cleared my cookies with NYT and resigned in to grab a new one but still getting that 401 unauthorized error after replacing the old cookie. I'll keep messing around with it.

**Comment by WhenInWome** [comment]
The extra weird thing is I have a separate script running to download the PDF locally (what I was doing before I found this repo) and that's been running fine through present with that original cookie. If the cookie expired you'd think they'd stop working on the same day.

https://i.imgur.com/tMklXqP.png

**Comment by JBlocklove** [comment]
Whoops, that's completely my bad, I put the wrong command there for you to test. Navigate to your install directory for the daily pdf (defaults to `~/.local/share/daily-pdf`) and run `./download-pdfs`. I'm assuming you set it up using the install script, so this should all be placed correctly. See if that gives you an unauthorized error.

**Comment by WhenInWome** [comment]
That one worked, thanks. Ran it through PuTTY and the RM2 rebooted and it showed up in the correct folder. Still not quite sure what went wrong/if it's fixed now, but it does have the new cookie so I'll see what it does tomorrow.

https://i.imgur.com/VyYwRS0.png

**Comment by JBlocklove** [comment]
Huh, weird. Here's hoping that it just starts working again!
